#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os, sys, shutil, subprocess, collections, time, datetime, shlex, getopt

class OrigFile():
	def __init__(self, inode1,inode2, path,type,date,size,perms):
		self.path = path
		self.i1 = inode1
		self.i2 = inode2
		self.type = type
		self.date = date
		self.size = size
		self.perms = perms

class DirFile():
	def __init__(self, inode, path, type, date, size, perms):
		self.i = inode
		self.path = path
		self.type = type
		self.date = date
		self.size = size
		self.perms = perms

def samefiles(f1, f2):
	# only take size in account for regular files
	if f1.type == "f" and f2.type == "f":
		return f1.date==f2.date and f1.perms==f2.perms and f1.size==f2.size
	else:
		return f1.type==f2.type and f1.date==f2.date and f1.perms==f2.perms

def ssh_master_init(sshlogin):
	import tempfile, atexit
	tmpdir = tempfile.mkdtemp()
	sshsock = os.path.join(tmpdir, "bsync_%r@%h:%p")
	try:
		subprocess.check_call(["ssh", "-fNMS", sshsock, sshlogin])
	except subprocess.CalledProcessError:
		sys.exit("Error: could not open SSH connection.")

	atexit.register(ssh_master_clean, tmpdir, sshsock, sshlogin)
	return sshsock

def ssh_master_clean(tmpdir, sshsock, sshlogin):
	# send exit signal to ssh master, this will remove the socket
	printv("Cleaning SSH master...")
	ret = subprocess.call(["ssh", "-S", sshsock, "-Oexit", sshlogin], stderr=subprocess.DEVNULL)
	if ret != 0:
	        print("Error in ssh master exit cmd." , file=sys.stderr)
		
	try:
		os.rmdir(tmpdir) # remove tmpdir (should be empty)
	except OSError:
		time.sleep(0.5)
		try:
			os.rmdir(tmpdir)
		except:
	        	print("Could not remove tmpdir: "+tmpdir, file=sys.stderr)

findformat = "%i\\0%P\\0%y\\0%T@\\0%s\\0%#m\\0"
# find test1/ -printf "%i\t%P\t%y\t%T@\t%s\t%#m\n"

def ssh_shell_init(sshsock, sshlogin):
	return subprocess.Popen([ "ssh", "-S"+sshsock, sshlogin, "sh -e" ], stdin=subprocess.PIPE, universal_newlines=True)

def rsync_init(sshsock, sshloginSrc,dirnameSrc, sshloginDst,dirnameDst):
	#rsync ssh/dir1 --> local/dir2
	#rsync local/dir1 --> ssh/dir2
	#
	#rsync ssh/dir2 --> local/dir1
	#rsync local/dir2 --> ssh/dir1
	if sshloginSrc == None:
		rsyncsrc = dirnameSrc+"/"
	else:
		rsyncsrc = sshloginSrc+":"+dirnameSrc+"/"

	if sshloginDst == None:
		rsyncdst = dirnameDst+"/"
	else:
		rsyncdst = sshloginDst+":"+dirnameDst+"/"

	args = [ "-a", "--files-from=-", "--from0", "--no-implied-dirs", "--out-format=rsync: %n%L" ]
	if sshsock != None:
		args.append("-e ssh -S"+sshsock)

	return subprocess.Popen(["rsync"]+args+[rsyncsrc, rsyncdst], stdin=subprocess.PIPE, universal_newlines=True)

def rsync_check(sshsock, sshloginSrc,dirnameSrc, sshloginDst,dirnameDst):
	if sshloginSrc == None:
		rsyncsrc = dirnameSrc+"/"
	else:
		rsyncsrc = sshloginSrc+":"+dirnameSrc+"/"
	if sshloginDst == None:
		rsyncdst = dirnameDst+"/"
	else:
		rsyncdst = sshloginDst+":"+dirnameDst+"/"

	args = [ "-anO", "--delete", "--out-format=%n%L", "--exclude=/.bsync-snap-*" ]
	if sshsock != None:
		args.append("-e ssh -S"+sshsock)

	diff = subprocess.check_output(["rsync"]+args+[rsyncsrc, rsyncdst], universal_newlines=True).split("\n")

	diff.remove("")
	diff.remove("./")

	if len(diff) != 0:
		sys.exit("Error: rsync_check differences:\n"+str(diff))

# TODO arguments and escapes...
# snap format: inode, path, type, date
def make_snapshot(sshsock, sshlogin,dirname, oldsnapname, newsnapname):
	global findformat

	cmd = "find %s -fprintf %s '%s'" % (dirname, dirname+"/"+newsnapname, findformat)
	if oldsnapname!=None:
		cmd+= " && rm -f "+dirname+"/"+oldsnapname

	if sshlogin==None:
		subprocess.check_call(cmd, shell=True)
	else:
		subprocess.check_call([ "ssh", "-S"+sshsock, sshlogin, cmd])

def make_snapshots(sshsock, sshlogin1,dir1name, sshlogin2,dir2name, oldsnapname):
	newsnapname = ".bsync-snap-"+datetime.datetime.now().strftime("%Y%m%d%H%M%S.%f")
	print("Updating filelists...")
	printv("Updating snap files: "+newsnapname+"...")
	make_snapshot(sshsock, sshlogin1,dir1name, oldsnapname,newsnapname)
	make_snapshot(sshsock, sshlogin2,dir2name, oldsnapname,newsnapname)

def get_find_fd(sshsock, sshlogin, dirname):
	global findformat
	if sshlogin==None:
		return subprocess.Popen([ "find", dirname, "-printf", findformat ], stdout=subprocess.PIPE, universal_newlines=True).stdout
	else:
		return subprocess.Popen([ "ssh", "-S"+sshsock, sshlogin, "find "+dirname+" -printf '"+findformat+"'" ], stdout=subprocess.PIPE, universal_newlines=True).stdout

def get_snap_fd(sshsock, sshlogin, dirname, snapname):
	if sshlogin==None:
		return open(dirname+"/"+snapname, "r")
	else:
		return subprocess.Popen([ "ssh", "-S"+sshsock, sshlogin, "cat "+dirname+"/"+snapname ], stdout=subprocess.PIPE, universal_newlines=True).stdout

def get_bsync_files(sshsock, sshlogin,dirname):
	files = set()
	if sshlogin==None:
		try:
			for f in os.listdir(dirname):
				if f.startswith(".bsync-"):
					files.add(f)
		except:
			sys.exit("Error: could not open directory: "+dirname)
	else:
		try:
			out = subprocess.check_output([ "ssh", "-S"+sshsock, sshlogin, "cd "+dirname+" && ( ls -1 .bsync-* 2>/dev/null || true )" ], universal_newlines=True)
		except subprocess.CalledProcessError:
			sys.exit("Error: could not open remote directory: "+dirname)
		
		files = set( out.split("\n") )

	snaps = set()
	ignorefile = None
	for f in files:
		if f == ".bsync-ignore":
			ignorefile = f
		elif f.startswith(".bsync-snap-"):
			snaps.add(f)
			
	return snaps, ignorefile

def get_ignores(ignorefile, sshsock, sshlogin,dirname):
	if ignorefile == None: return set()

	if sshlogin==None:
		with open(dirname+"/"+ignorefile) as fd:
			out = fd.read()
	else:
		out = subprocess.check_output([ "ssh", "-S"+sshsock, sshlogin, "cat "+dirname+"/"+ignorefile ], universal_newlines=True)

	lines = out.split("\n")

	ignores = set()
	for l in lines:
		if l != "":
			if not l.endswith("/"): l+="/"
			ignores.add(l)
	return ignores

def ignorepath(path, type, ignoreset):
	if path == "" or path.startswith(".bsync-"):
		return True
	else:
		for ignore in ignoreset:
			if (path+"/").startswith(ignore):
				return True
	
	return False

# http://stackoverflow.com/questions/9237246/python-how-to-read-file-with-nul-delimited-lines
# http://bugs.python.org/issue1152248
def fileLineIter(inputFile,
                 inputNewline="\n",
                 outputNewline=None,
                 readSize=8192):
   """Like the normal file iter but you can set what string indicates newline.

   The newline string can be arbitrarily long; it need not be restricted to a
   single character. You can also set the read size and control whether or not
   the newline string is left on the end of the iterated lines.  Setting
   newline to '\0' is particularly good for use with an input file created with
   something like "os.popen('find -print0')".
   """
   if outputNewline is None: outputNewline = inputNewline
   partialLine = ''
   while True:
       charsJustRead = inputFile.read(readSize)
       if not charsJustRead: break
       partialLine += charsJustRead
       lines = partialLine.split(inputNewline)
       partialLine = lines.pop()
       for line in lines: yield line + outputNewline.rstrip('\0') # little mod
   if partialLine: yield partialLine.rstrip('\0') # little mod

def read_file_record(gen):
	i=p=t=d=s=perms=None
	try:
		i,p,t,d,s,perms = next(gen),next(gen),next(gen),next(gen),next(gen),next(gen)
	except StopIteration:
		if i==None and p==None and t==None and d==None and s==None and perms==None:
			return None
		else:
			sys.exit("Error: snap filelists not coherent.")

	d = d.split(".")[0]	# truncate date to seconds
	if t=="d": d=s="0"	# ignore dates/size for dirs (set to zero)

	return i,p,t,d,s,perms

def load_orig(sshsock, sshlogin1,dir1name, sshlogin2,dir2name):
	snaps1, ignorefile1 = get_bsync_files(sshsock, sshlogin1,dir1name)
	snaps2, ignorefile2 = get_bsync_files(sshsock, sshlogin2,dir2name)

	ignores1 = get_ignores(ignorefile1, sshsock, sshlogin1,dir1name)
	ignores2 = get_ignores(ignorefile2, sshsock, sshlogin2,dir2name)
	ignores = ignores1 | ignores2

	common_snaps = snaps1.intersection(snaps2)
	orig = collections.OrderedDict()
	if len(common_snaps) == 0:
		print("Old filelist not found. Starting with empty history.")
		return (None, orig, ignores) #empty snap and orig

	snapname = max(common_snaps) #the most recent snapshot

	printv("Loading "+snapname+"...")

	fd1 = get_snap_fd(sshsock, sshlogin1, dir1name, snapname)
	fd2 = get_snap_fd(sshsock, sshlogin2, dir2name, snapname)
	gen1 = fileLineIter(fd1, inputNewline='\0')
	gen2 = fileLineIter(fd2, inputNewline='\0')

	# iterate on gen1 to fill orig
	# first fill with 1st snap, then with 2nd snap, because the order can be different (in find output)
	record = read_file_record(gen1)
	while record != None:
		inode,path,type,date,size,perms = record

		if not ignorepath(path, type, ignores):
			orig[path] = OrigFile(inode,None, path,type,date,size,perms)
		
		record = read_file_record(gen1)

	# iterate on gen2, fill inodes for dir2 and check for consistency
	record = read_file_record(gen2)
	while record != None:
		inode,path,type,date,size,perms = record

		if not ignorepath(path, type, ignores):
			#path not in orig: can happen if using ignore, then removing ignore, path will be considered as new
			if path in orig:
				origfile = orig[path]
				if origfile.type != type or origfile.date != date or origfile.size != size or origfile.perms != perms:
					sys.exit("Error: difference in snaps for path: "+path) 

				origfile.i2 = inode #set the second inode
		
		record = read_file_record(gen2)

	fd1.close()
	fd2.close()

	return snapname, orig, ignores

def load_dir(sshsock, sshlogin, dirname, ignores):
	dir = collections.OrderedDict()

	fd = get_find_fd(sshsock, sshlogin, dirname)
	gen = fileLineIter(fd, inputNewline='\0')

	record = read_file_record(gen)
	while record != None:
		inode,path,type,date,size,perms = record

		if not ignorepath(path, type, ignores):
			dir[path] = DirFile(inode, path, type, date, size, perms)
		
		record = read_file_record(gen)

	fd.close()
	
	return dir

def getdatestr(f):
	return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime( int(f.date.split(".")[0]) ))

# conflict can be on type, date, size, perms
def ask_conflict(f1, f2, path):

	if f1 == None:
		p1 = "*deleted*"
		p2 = f2.type+" "+f2.perms+" "+f2.size+" ("+getdatestr(f2)+")"
	elif f2 == None:
		p1 = f1.type+" "+f1.perms+" "+f1.size+" ("+getdatestr(f1)+")"
		p2 = "*deleted*"
	else:
		p1=p2=""
		if f1.type != f2.type:
			p1+= f1.type
			p2+= f2.type

		if f1.perms != f2.perms:
			p1+= " "+f1.perms
			p2+= " "+f2.perms
		
		# size and date are meaningless for dirs. conflicts will not be on them
		# don't display them if one side is a directory
		if f1.size != f2.size and f1.type!="d" and f2.type!="d":
			p1+= " "+f1.size
			p2+= " "+f2.size

		if f1.date != f2.date and f1.type!="d" and f2.type!="d":
			p1+= " ("+getdatestr(f1)+")"
			p2+= " ("+getdatestr(f2)+")"

	print("Conflicting changes on: "+path)
	print_action("conflict", p1, "???", p2)

	resp = "invalid"
	while resp != "1" and resp != "2":
		resp = input("Which change do I keep [1/2]: ")
	return resp

#### file actions
def remove(shproc, path):
	if shproc == None:
		os.remove(path)
	else:
		shproc.stdin.write("rm "+shlex.quote(path)+"\n")
		shproc.stdin.flush()

def removedir(shproc, path):
	if shproc == None:
		try:
			os.rmdir(path)
		except OSError as e:
			#pass
			print("Warning: "+str(e)) # can happen: dir removed in 1, file dir/f added in 2
	else:
		shproc.stdin.write("rmdir "+shlex.quote(path)+" || true\n")
		shproc.stdin.flush()

# TODO security for shell injection
def mkdir(shproc, path, perms):
	if shproc == None:
		os.mkdir(path, int(perms, 8) )
	else:
		shproc.stdin.write("mkdir -m"+perms+" "+shlex.quote(path)+"\n")
		shproc.stdin.flush()

def move(shproc, src, dst, perms):
	if shproc == None:
		os.rename(src, dst)
		if perms!=None:
			os.chmod(dst, int(perms, 8) )
	else:
		shproc.stdin.write("mv "+shlex.quote(src)+" "+shlex.quote(dst)+"\n")
		if perms!=None:
			shproc.stdin.write("chmod "+perms+" "+shlex.quote(dst)+"\n")
		shproc.stdin.flush()

def rsync(rsyncproc, path):
	rsyncproc.stdin.write(path+"\0")
	rsyncproc.stdin.flush()

def printv(s):
	global verbose
	if verbose: print(s)

def print_action(action, path1, arrow, path2):
	global console_width
	w = 0
	if console_width != 0:
		w = (console_width -1-3-2 -1-11) // 2

	action = "("+action+")" if action!="" else ""
	
	print( path1.ljust(w) +" "+arrow+"  "+ path2.ljust(w) +" "+action )

def print_files(fo, f1, f2):
	print("%s: i:%s d:%s | i:%s d:%s (orig)" % (fo.path, fo.i1, fo.date, fo.i2, fo.date))
	f1str = f1str = "i:"+f1.i+" d:"+str(f1.date) if f1!=None else ""
	f2str = f2str = "i:"+f2.i+" d:"+str(f2.date) if f2!=None else ""
	print("%s: %s | %s" % (fo.path, f1str, f2str))

def print_files12(path, f1, f2):
	f1str = f1str = "i:"+f1.i+" d:"+str(f1.date) if f1!=None else ""
	f2str = f2str = "i:"+f2.i+" d:"+str(f2.date) if f2!=None else ""
	print("%s: %s | %s" % (path, f1str, f2str))

def print_actions(dirnum, mkdirs,moves,rm,rmdirs, copy,sync):
	##### actions involving one side
	arrow = "-->"
	if dirnum==1:
		arrow = "<--"

	# mkdirss must be done before
	for f in mkdirs:
		if dirnum==2:
			print_action("mkdir", f.path+"/", "-->", "")
		else:
			print_action("mkdir", "", "<--", f.path+"/")

	# moves
	for fromfile, targetfile in moves:
		if dirnum==2:
			print_action("move", targetfile.path, "-->", "from:"+fromfile.path)
		else:
			print_action("move", "from:"+fromfile.path, "<--", targetfile.path)

	# removes, after the check moves step
	for f in rm.values():
		if dirnum==2:
			print_action("rm", "", "-->", f.path)
		else:
			print_action("rm", f.path, "<--", "")

	# rmdirs must be done after
	for path in rmdirs:
		if dirnum==2:
			print_action("rmdir", "", "-->", path)
		else:
			print_action("rmdir", path, "<--", "")

	##### actions involving a transfer
	# finish with copy and sync
	for path in copy:
		if dirnum==2:
			print_action("copy", path, "-->", "")
		else:
			print_action("copy", "", "<--", path)
	for path in sync:
		if dirnum==2:
			print_action("sync", path, "-->", path)
		else:
			print_action("sync", path, "<--", path)
# end print_actions

def apply_actions(dirnum, sshsock,
	sshlogin1,dir1name, sshlogin2,dir2name,
	mkdirs, moves, rm, rmdirs, copy, sync
	):

	##### actions involving one side
	sshlogin = sshlogin2
	arrow = "-->"
	if dirnum==1:
		sshlogin = sshlogin1
		arrow = "<--"

	shproc = None
	# if we need a ssh shell
	if ( (dirnum==2 and sshlogin2!=None) or (dirnum==1 and sshlogin1!=None) ) \
	   and ( mkdirs!=[] or copy!=[] or rmdirs!=[] or len(rm)!=0 ):
		shproc = ssh_shell_init(sshsock, sshlogin)

	# mkdirss must be done before
	os.umask(0000) #disable umask to allow for any mkdirs
	for f in mkdirs:
		if dirnum==2:
			mkdir(shproc, dir2name+"/"+f.path, f.perms)
		else:
			mkdir(shproc, dir1name+"/"+f.path, f.perms)

	# moves
	for fromfile, targetfile in moves:
		perms = None if fromfile.perms == targetfile.perms else targetfile.perms
		if dirnum==2:
			move(shproc, dir2name+"/"+fromfile.path, dir2name+"/"+targetfile.path, perms)
		else:
			move(shproc, dir1name+"/"+fromfile.path, dir1name+"/"+targetfile.path, perms)

	# removes, after the check moves step
	for f in rm.values():
		if dirnum==2:
			remove(shproc, dir2name+"/"+f.path)
		else:
			remove(shproc, dir1name+"/"+f.path)

	# rmdirs must be done after
	for path in rmdirs:
		if dirnum==2:
			removedir(shproc, dir2name+"/"+path)
		else:
			removedir(shproc, dir1name+"/"+path)

	if shproc != None:
		shproc.stdin.close()
		shproc.wait() # wait shell process to exit
		if shproc.returncode != 0:
			sys.exit("Error in shell process.")

	##### actions involving a transfer
	rsyncproc = None
	# if we need rsync (at least one remote dir, and some copies/sync to do)
	if copy!=[] or sync!=[]:
		if dirnum==2:
			rsyncproc = rsync_init(sshsock, sshlogin1,dir1name, sshlogin2,dir2name)
		else:
			rsyncproc = rsync_init(sshsock, sshlogin2,dir2name, sshlogin1,dir1name)

	# finish with copy and sync
	for path in copy:
		rsync(rsyncproc, path)
	for path in sync:
		rsync(rsyncproc, path)

	if rsyncproc != None:
		rsyncproc.stdin.close()
		rsyncproc.wait()
		if rsyncproc.returncode != 0:
			sys.exit("Error in rsync process.")
# end do_actions

def check_moves(copy, rm):
	# check if we can move instead of rm+copy
	# return resulting copy/rm actions + moves
	moves = []
	copyreal = []
	for fsrc in copy: # f1 in copy12
		# we must copy f1 to dir2
		# to use a move: search for f1 inode
		# f1.i == fo.i1 <> fo.i2 == f2.i
		fcandidate = rm.get(fsrc.i, None) # check if we can use a move

		# check date to be sure that no change on file.
		if fcandidate != None and fcandidate.type == fsrc.type and fcandidate.date == fsrc.date and fcandidate.size == fsrc.size:
			moves.append( (fcandidate, fsrc) )
			rm.pop(fsrc.i)
		else:	
			copyreal.append(fsrc.path)

	return copyreal, rm, moves

def usage():
	usage = "Usage: bsync [-v] DIR1 DIR2"
	print(usage , file=sys.stderr)

#####################################################

#### process commandline args
try:
	opts, args = getopt.gnu_getopt(sys.argv[1:], "vc")
except getopt.GetoptError as err:
	print(err, file=sys.stderr)
	usage()
	sys.exit(2)

verbose = False
check = False
for o, a in opts:
	if o == "-v":
		verbose = True
	elif o == "-c":
		check = True
	else:
		assert False, "unhandled option"

if len(args) != 2:
	usage()
	sys.exit(2)

dir1name = args[0]
dir2name = args[1]

# try to get console width, for displaying actions, if running interactive
try:
	height, width = subprocess.check_output(['stty', 'size'], universal_newlines=True, stderr=subprocess.DEVNULL).split()
	console_width = int(width)
except:
	console_width = 0

# get sshlogin vars
sshlogin1 = sshlogin2 = None
if ':' in dir1name:
	sshlogin1, dir1name = dir1name.split(':', 1)
if ':' in dir2name:
	sshlogin2, dir2name = dir2name.split(':', 1)
if sshlogin1!=None and sshlogin2!=None:
	sys.exit("Error: only one remote directory supported.")

sshsock = None
if sshlogin1!=None or sshlogin2!=None:
	sshsock = ssh_master_init(sshlogin1 if sshlogin1!=None else sshlogin2)

print("Loading filelists...")

printv("Loading original filelist from snap files...")
snapname, origlist, ignores = load_orig(sshsock, sshlogin1,dir1name, sshlogin2,dir2name)

printv("Loading dir1 filelist...")
dir1 = load_dir(sshsock, sshlogin1, dir1name, ignores)
printv("Loading dir2 filelist...")
dir2 = load_dir(sshsock, sshlogin2, dir2name, ignores)

printv("Analysing original paths...")
mkdir1 = []
mkdir2 = []
rmdirs1 = []
rmdirs2 = []
rm1 = collections.OrderedDict()
rm2 = collections.OrderedDict()
copy12 = []
copy21 = []
sync12 = []
sync21 = []
# process all paths from snapshot
for path, fo in origlist.items():
	# f1==None f2==None				deleted both sides
	# f1==None f2=!None f2.d==fo.d			f1 chg only
	# f1==None f2=!None f2.d!=fo.d			conflict
	# f1!=None f2==None f1.d==fo.d			f2 chg only
	# f1!=None f2==None f1.d!=fo.d			conflict
	# f1!=None f2!=None f1.d==fo.d f2.d==fo.d	no change
	# f1!=None f2!=None f1.d==fo.d f2.d!=fo.d	f2 chg only
	# f1!=None f2!=None f1.d!=fo.d f2.d==fo.d	f1 chg only
	# f1!=None f2!=None f1.d!=fo.d f2.d!=fo.d	conflict

	f1 = dir1[path] if path in dir1 else None
	f2 = dir2[path] if path in dir2 else None

	if f1 == None and f2 == None:
		# deleted both sides --> nothing to do
		pass
	elif f1 != None and f2 != None and samefiles(f1,f2):
		# same file contents --> nothing to do
		pass
	elif f2 != None and samefiles(f2,fo):
		# no f2 change --> f1 change only
		if f1 == None:
			# f1 deleted --> delete f2
			if f2.type == "d": # f2 isdir
				rmdirs2.append(path)
			else:
				rm2[fo.i1] = f2
		else:
			# f1 != None and f1 != fo.date --> f1 mod --> mod f2
			sync12.append(path)
	elif f1 != None and samefiles(f1,fo):
		# no f1 change --> f2 change only
		if f2 == None:
			if f1.type == "d": #f1 isdir
				rmdirs1.append(path)
			else:
				rm1[fo.i2] = f1
		else:
			sync21.append(path)
	else:
		# f1 change and f2 change --> confict
		# f1 != None and f2 != None --> f1.date != f2.date (!= fo.date)
		# f1 == None and f2 != None
		# f1 != None and f2 == None

		tokeep = ask_conflict(f1, f2, path);
		if tokeep == "1":
			if f1 == None:
				if f2.type == "d": # f2 isdir
					rmdirs2.append(path)
				else:
					rm2[fo.i1] = f2
			else:
				if f2 == None:
					if f1.type == "d":
						mkdir2.append(f1)
					else:
						copy12.append(f1)
				else:
					sync12.append(path)
		else: # tokeep == 2
			if f2 == None:
				if f1.type == "d": # f1 isdir
					rmdirs1.append(path)
				else:
					rm1[fo.i2] = f1
			else:
				if f1 == None:
					if f2.type == "d":
						mkdir1.append(f2)
					else:
						copy21.append(f2)
				else:
					sync21.append(path)
	#ifend

	dir1.pop(path, None)
	dir2.pop(path, None)
#forend

printv("Analysing remaining new paths in dir1...")
# process new paths in dir1
for path, f1 in dir1.items():
	f2 = dir2[path] if path in dir2 else None

	if f2 != None and samefiles(f2,f1):
		# f1 and f2 added but same files --> nothing to do
		pass
	elif f2 == None:
		# adding in d2
		if f1.type == "d":
			mkdir2.append(f1)
		else:
			copy12.append(f1)
	else:
		# f2!=None and f2.date != f1.date --> conflict
		tokeep = ask_conflict(f1, f2, path);
		if tokeep == "1":
			sync12.append(path)
		else: # tokeep == 2
			sync21.append(path)

	dir2.pop(path, None)

printv("Analysing remaining new paths in dir2...")
# process remaining new paths in dir2
for path, f2 in dir2.items():
	f1 = dir1[path] if path in dir1 else None

	if f1 != None and samefiles(f1,f2):
		pass
	elif f1 == None:
		if f2.type == "d":
			mkdir1.append(f2)
		else:
			copy21.append(f2)
	else:
		tokeep = ask_conflict(f1, f2, path);
		if tokeep == "1":
			sync12.append(path)
		else: # tokeep == 2
			sync21.append(path)

# moves detection
copy12, rm2, moves2 = check_moves(copy12, rm2)
copy21, rm1, moves1 = check_moves(copy21, rm1)

rmdirs1.sort(reverse=True) # TODO someth cleaner than sort?
rmdirs2.sort(reverse=True) # TODO someth cleaner than sort?

# ACTION!
# ACTIONS in dir2 -->
# ACTIONS in dir1 <--

# if no action to do
if len(mkdir1)==0 and len(moves1)==0 and len(rm1)==0 and len(rmdirs1)==0 and len(copy21)==0 and len(sync21)==0 and \
   len(mkdir2)==0 and len(moves2)==0 and len(rm2)==0 and len(rmdirs2)==0 and len(copy12)==0 and len(sync12)==0:
	if check: rsync_check(sshsock, sshlogin1,dir1name, sshlogin2,dir2name)
	print("Identical directories. Nothing to do.")
	if snapname == None:
		make_snapshots(sshsock, sshlogin1,dir1name, sshlogin2,dir2name, snapname)
	sys.exit()

print_action("", args[0], "   ", args[1])
print_actions(2, mkdir2,moves2,rm2,rmdirs2, copy12,sync12)
print_actions(1, mkdir1,moves1,rm1,rmdirs1, copy21,sync21)

resp = "invalid"
while resp != "y" and resp != "n":
	resp = input("Apply actions? [y/N] ").lower()
	if resp == "": resp = "n"
if resp == "n":
	print("Leaving files in place.")
	sys.exit()

print("Applying actions...")

printv("Applying actions in dir2...")
apply_actions(2, sshsock,
	sshlogin1,dir1name, sshlogin2,dir2name,
	mkdir2,moves2,rm2,rmdirs2, copy12,sync12
	)

printv("Applying actions in dir1...")
apply_actions(1, sshsock,
	sshlogin1,dir1name, sshlogin2,dir2name,
	mkdir1,moves1,rm1,rmdirs1, copy21,sync21
	)

if check: rsync_check(sshsock, sshlogin1,dir1name, sshlogin2,dir2name)

make_snapshots(sshsock, sshlogin1,dir1name, sshlogin2,dir2name, snapname)

print("Done!")
